# Generated by Django 3.0.3 on 2020-04-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='usuario',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
