# Generated by Django 3.0.3 on 2020-04-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_registros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='registro_id',
        ),
        migrations.DeleteModel(
            name='Registros',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
